name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Build & publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/zealot
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build
        run: python3 -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
